-------------------------------------------------------------------------------
--CREATE JOINED TABLES WITH REGRESSION ANALYSIS (3 TYPES) BY INDIVIDUAL CANCER TYPES--
-------------------------------------------------------------------------------

CREATE TABLE Cancer_ML_Regressions(economic_factors char (100), Decision_Tree_Liver_cancer decimal(30, 17),
	Decision_Tree_Kidney_cancer decimal(30, 17),
	Decision_Tree_Tracheal_bronchus_lung_cancer decimal(30, 17),
	Decision_Tree_Malignant_skin_melanoma decimal(30, 17),
	Decision_Tree_Leukemia_cancer decimal(30, 17),
	Decision_Tree_Breast_cancer decimal(30, 17),
	Decision_Tree_Prostate_cancer decimal(30, 17),
	Decision_Tree_Thyroid_cancer decimal(30, 17),
	Decision_Tree_Bladder_cancer decimal(30, 17),
	Decision_Tree_Uterine_cancer decimal(30, 17),
	Decision_Tree_Ovarian_cancer decimal(30, 17),
	Decision_Tree_Cervical_cancer decimal(30, 17),
	Decision_Tree_Non_Hodgkin_lymphoma decimal(30, 17),
	Decision_Tree_Pancreatic_cancer decimal(30, 17),
	Decision_Tree_Colon_and_rectum_cancer decimal(30, 17),
	Linear_Regression_Liver_cancer decimal(30, 17),
	Linear_Regression_Kidney_cancer decimal(30, 17),
	Linear_Regression_Tracheal_bronchus_lung_cancer decimal(30, 17),
	Linear_Regression_Malignant_skin_melanoma decimal(30, 17),
	Linear_Regression_Leukemia_cancer decimal(30, 17),
	Linear_Regression_Breast_cancer decimal(30, 17),
	Linear_Regression_Prostate_cancer decimal(30, 17),
	Linear_Regression_Thyroid_cancer decimal(30, 17),
	Linear_Regression_Bladder_cancer decimal(30, 17),
	Linear_Regression_Uterine_cancer decimal(30, 17),
	Linear_Regression_Ovarian_cancer decimal(30, 17),
	Linear_Regression_Cervical_cancer decimal(30, 17),
	Linear_Regression_Non_Hodgkin_lymphoma decimal(30, 17),
	Linear_Regression_Pancreatic_cancer decimal(30, 17),
	Linear_Regression_Colon_and_rectum_cancer decimal(30, 17),
	Random_Forest_Liver_cancer decimal(30, 17),
	Random_Forest_Kidney_cancer decimal(30, 17),
	Random_Forest_Tracheal_bronchus_lung_cancer decimal(30, 17),
	Random_Forest_Malignant_skin_melanoma decimal(30, 17),
	Random_Forest_Leukemia_cancer decimal(30, 17),
	Random_Forest_Breast_cancer decimal(30, 17),
	Random_Forest_Prostate_cancer decimal(30, 17),
	Random_Forest_Thyroid_cancer decimal(30, 17),
	Random_Forest_Bladder_cancer decimal(30, 17),
	Random_Forest_Uterine_cancer decimal(30, 17),
	Random_Forest_Ovarian_cancer decimal(30, 17),
	Random_Forest_Cervical_cancer decimal(30, 17),
	Random_Forest_Non_Hodgkin_lymphoma decimal(30, 17),
	Random_Forest_Pancreatic_cancer decimal(30, 17),
	Random_Forest_Colon_and_rectum_cancer decimal(30, 17)
);
------------------------------------------------------
---JOINING DATA INTO 1 ML REGRESSION TABLE
------------------------------------------------------

INSERT INTO cancer_ml_regressions(economic_factors, Decision_Tree_Liver_cancer,
	Decision_Tree_Kidney_cancer,
	Decision_Tree_Tracheal_bronchus_lung_cancer,
	Decision_Tree_Malignant_skin_melanoma,
	Decision_Tree_Leukemia_cancer,
	Decision_Tree_Breast_cancer,
	Decision_Tree_Prostate_cancer,
	Decision_Tree_Thyroid_cancer,
	Decision_Tree_Bladder_cancer,
	Decision_Tree_Uterine_cancer,
	Decision_Tree_Ovarian_cancer,
	Decision_Tree_Cervical_cancer,
	Decision_Tree_Non_Hodgkin_lymphoma,
	Decision_Tree_Pancreatic_cancer,
	Decision_Tree_Colon_and_rectum_cancer,
	Linear_Regression_Liver_cancer,
	Linear_Regression_Kidney_cancer,
	Linear_Regression_Tracheal_bronchus_lung_cancer,
	Linear_Regression_Malignant_skin_melanoma,
	Linear_Regression_Leukemia_cancer,
	Linear_Regression_Breast_cancer,
	Linear_Regression_Prostate_cancer,
	Linear_Regression_Thyroid_cancer,
	Linear_Regression_Bladder_cancer,
	Linear_Regression_Uterine_cancer,
	Linear_Regression_Ovarian_cancer,
	Linear_Regression_Cervical_cancer,
	Linear_Regression_Non_Hodgkin_lymphoma,
	Linear_Regression_Pancreatic_cancer,
	Linear_Regression_Colon_and_rectum_cancer,
	Random_Forest_Liver_cancer,
	Random_Forest_Kidney_cancer,
	Random_Forest_Tracheal_bronchus_lung_cancer,
	Random_Forest_Malignant_skin_melanoma,
	Random_Forest_Leukemia_cancer,
	Random_Forest_Breast_cancer,
	Random_Forest_Prostate_cancer,
	Random_Forest_Thyroid_cancer,
	Random_Forest_Bladder_cancer,
	Random_Forest_Uterine_cancer,
	Random_Forest_Ovarian_cancer,
	Random_Forest_Cervical_cancer,
	Random_Forest_Non_Hodgkin_lymphoma,
	Random_Forest_Pancreatic_cancer,
	Random_Forest_Colon_and_rectum_cancer)
SELECT dtr.index_i, dtr.dt_liver, dtr.dt_Kidney, dtr.dt_lung, dtr.dt_skin,dtr.dt_Leukemia,
	dtr.dt_Breast, dtr.dt_Prostate, dtr.dt_Thyroid, dtr.dt_Bladder, dtr.dt_Uterine, dtr.dt_Ovarian,
	dtr.dt_Cervical, dtr.dt_Non_Hodgkin, dtr.dt_Pancreatic, dtr.dt_Colon,
	lnr.lin_reg_liver, lnr.lin_reg_Kidney, lnr.lin_reg_lung, lnr.lin_reg_skin, lnr.lin_reg_leukemia,
	lnr.lin_reg_breast, lnr.lin_reg_prostate, lnr.lin_reg_thyroid, lnr.lin_reg_bladder, lnr.lin_reg_uterine,
	lnr.lin_reg_ovarian, lnr.lin_reg_cervical, lnr.lin_reg_non_hodgkin, lnr.lin_reg_pancreatic,
	lnr.lin_reg_colon,
	rfr.rf_liver, rfr.rf_kidney, rfr.rf_lung, rfr.rf_skin, rfr.rf_leukemia, rfr.rf_breast, rfr.rf_prostate, 
	rfr.rf_thyroid, rfr.rf_bladder, rfr.rf_uterine, rfr.rf_ovarian, rfr.rf_cervical, rfr.rf_non_hodgkin, rfr.rf_pancreatic,
	rfr.rf_colon
FROM dtr
JOIN lnr
ON dtr.index_i = lnr.index_id
JOIN rfr
ON lnr.index_id = rfr.id_index; 

SELECT * FROM cancer_ml_regressions;